services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: store_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        container_name: store_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: postgres:14-alpine
        container_name: store_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: store_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
